### ISSUE TITLE
Setting up puppeteer in a docker environment using sail

### ISSUE THREAD

**Issue by Joemires** [zoonru/puphpeteer#14]
Hello guys!
Please I need help with setting up my puppeteer in a docker environment 
I'm using laravel sail and will appreciate having a container with chrome setup where I can connect my puppeteer to, I have seen someone do it with node, something like this:
```yml
chrome:
    image: 'browserless/chrome'
    ports: 
        - '${BROWSERLESS_CHROME_PORT:-3000}:3000'
    networks:
        - sail
    environment:
        - CONNECTION_TIMEOUT=-1       
```

later in the code
```js
const browser = await puppeteer.connect({
    browserWSEndpoint: "ws://chrome:3000",
});
```

**Comment by dsebastien** [comment]
I'm also curious about this. @Joemires, did you manage to make it work?

**Comment by Joemires** [comment]
Yes I did @dsebastien 
Your docker compose configuration
```yml
chrome:
    image: 'browserless/chrome'
    ports: 
        - '${BROWSERLESS_CHROME_PORT:-3000}:3000'
    networks:
        - sail
    environment:
        - CONNECTION_TIMEOUT=-1       
```

later in the code
```js
$client = $puppeteer->connect([
    'browserWSEndpoint' => env('BROWSER_WS_ENDPOINT') ?: 'ws://localhost:300'
]);
```
